<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$baseurl    = $storeManager->getStore()->getBaseUrl();
$helper = $objectManager->get('Jewel\CartCsv\Helper\Data'); 
if($helper->isEnable() == 1 && $customerSession->isLoggedIn()){ ?>
<a href="<?=  $baseurl ?>cartcsv/index/index/">
    <button>Csv Download</button>
</a>
<?php } ?>